// @flow

const codes: {
  BAD_REQUEST: number,
  UNAUTHORIZED: number,
  FORBIDDEN: number,
  DATA_NOT_FOUND: number,
  METHOD_NOT_ALLOWED: number,
  UNSUPPORTED_MEDIA_TYPE: number,
  RATE_LIMIT_EXCEEDED: number,
  INTERNAL_SERVICE_ERROR: number,
  SERVICE_UNAVAILABLE: number,
  GATEWAY_TIMEOUT: number
} = {
  BAD_REQUEST: 400,
  UNAUTHORIZED: 401,
  FORBIDDEN: 403,
  DATA_NOT_FOUND: 404,
  METHOD_NOT_ALLOWED: 405,
  UNSUPPORTED_MEDIA_TYPE: 415,
  RATE_LIMIT_EXCEEDED: 429,
  INTERNAL_SERVICE_ERROR: 500,
  SERVICE_UNAVAILABLE: 503,
  GATEWAY_TIMEOUT: 504
}

export default codes