const CHAMPION_MASTERY = {
  GET_ALL_CHAMPION_MASTERIES: 'CHAMPION_MASTERY.GET_ALL_CHAMPION_MASTERIES',
  GET_CHAMPION_MASTERY: 'CHAMPION_MASTERY.GET_CHAMPION_MASTERY',
  GET_CHAMPION_MASTERY_SCORE: 'GET_CHAMPION_MASTERY_SCORE',
};

const CHAMPION = {
  GET_CHAMPIONS: 'CHAMPION.GET_CHAMPIONS',
  GET_CHAMPION_BY_ID: 'CHAMPION.GET_CHAMPION_BY_ID',
};

const LEAGUE = {
  GET_CHALLENGER_LEAGUE: 'LEAGUE.GET_CHALLENGER_LEAGUE',
  GET_ALL_LEAGUES_FOR_SUMMONER: 'LEAGUE.GET_ALL_LEAGUES_FOR_SUMMONER',
  GET_LEAGUE_BY_ID: 'LEAGUE.GET_BY_ID',
  GET_MASTER_LEAGUE: 'LEAGUE.GET_MASTER_LEAGUE',
  GET_ALL_LEAGUE_POSITIONS_FOR_SUMMONER:
    'LEAGUE.GET_ALL_LEAGUE_POSITIONS_FOR_SUMMONER',
};

const STATIC = {
  GET_CHAMPION_LIST: 'STATIC.GET_CHAMPION_LIST',
  GET_CHAMPION_BY_ID: 'STATIC.GET_CHAMPION_BY_ID',
  GET_ITEM_LIST: 'STATIC.GET_ITEM_LIST',
  GET_ITEM_BY_ID: 'STATIC.GET_ITEM_BY_ID',
  GET_LANGUAGE_STRINGS: 'STATIC.GET_LANGUAGE_STRINGS',
  GET_LANGUAGES: 'STATIC.GET_LANGUAGES',
  GET_MAP_DATA: 'STATIC.GET_MAP_DATA',
  GET_MASTERY_LIST: 'STATIC.GET_MASTERY_LIST',
  GET_MASTERY_BY_ID: 'STATIC.GET_MASTERY_BY_ID',
  GET_PROFILE_ICONS: 'STATIC.GET_PROFILE_ICONS',
  GET_REALM: 'STATIC.GET_REALM',
  GET_RUNE_LIST: 'STATIC.GET_RUNE_LIST',
  GET_RUNE_BY_ID: 'STATIC.GET_RUNE_BY_ID',
  GET_SUMMONER_SPELL_LIST: 'STATIC.GET_SUMMONER_SPELL_LIST',
  GET_SUMMONER_SPELL_BY_ID: 'STATIC.GET_SUMMONER_SPELL_BY_ID',
  GET_VERSIONS: 'STATIC.GET_VERSIONS',
};

const LOL_STATUS = {
  GET_SHARD_DATA: 'LOL_STATUS.GET_SHARD_DATA',
};

const MASTERIES = {
  GET_MASTERY_PAGES_BY_SUMMONER_ID:
    'MASTERIES.GET_MASTERY_PAGES_BY_SUMMONER_ID',
};

const MATCH = {
  GET_MATCH: 'MATCH.GET_MATCH',
  GET_MATCHLIST: 'MATCH.GET_MATCHLIST',
  GET_RECENT_MATCHLIST: 'MATCH.GET_RECENT_MATCHLIST',
  GET_MATCH_TIMELINE: 'MATCH.GET_MATCH_TIMELINE',
};

const RUNES = {
  GET_RUNE_PAGES_BY_SUMMONER_ID: 'RUNES.GET_RUNE_PAGES_BY_SUMMONER_ID',
};

const SPECTATOR = {
  GET_CURRENT_GAME_INFO_BY_SUMMONER:
    'SPECTATOR.GET_CURRENT_GAME_INFO_BY_SUMMONER',
  GET_FEATURED_GAMES: 'SPECTATOR.GET_FEATURED_GAMES',
};

const SUMMONER = {
  GET_BY_ACCOUNT_ID: 'SUMMONER.GET_BY_ACCOUNT_ID',
  GET_BY_SUMMONER_NAME: 'SUMMONER.GET_BY_SUMMONER_NAME',
  GET_BY_SUMMONER_ID: 'SUMMONER.GET_BY_SUMMONER_ID',
};

export default {
  CHAMPION_MASTERY,
  CHAMPION,
  LEAGUE,
  STATIC,
  LOL_STATUS,
  MASTERIES,
  MATCH,
  RUNES,
  SPECTATOR,
  SUMMONER,
};
