const CHAMPION_MASTERY = {
    GET_ALL_CHAMPION_MASTERIES: 'CHAMPION_MASTERY.GET_ALL_CHAMPION_MASTERIES',
    GET_CHAMPION_MASTERY: 'CHAMPION_MASTERY.GET_CHAMPION_MASTERY',
    GET_CHAMPION_MASTERY_SCORE: 'CHAMPION_MASTERY.GET_CHAMPION_MASTERY_SCORE',

    // V4
    GET_ALL_CHAMPION_MASTERIES_V4:
        'CHAMPION_MASTERY.GET_ALL_CHAMPION_MASTERIES_V4',
    GET_CHAMPION_MASTERY_V4: 'CHAMPION_MASTERY.GET_CHAMPION_MASTERY_V4',
    GET_CHAMPION_MASTERY_SCORE_V4:
        'CHAMPION_MASTERY.GET_CHAMPION_MASTERY_SCORE_V4',
}

const CHAMPION = {
    GET_CHAMPION_ROTATIONS: 'CHAMPION.GET_CHAMPION_ROTATIONS',
}

const DDRAGON = {
    CHAMPION_GET: 'DDRAGON.CHAMPION.GET',
    CHAMPION_GET_DATA_BY_ID: 'DDRAGON.CHAMPION.HELPER.GET_DATA_BY_ID', // { Aatrox: { ... id: '5', key: "Aatrox" } }
    CHAMPION_GET_DATA_BY_ID_PARENT_TOO:
        'DDRAGON.CHAMPION.HELPER.GET_DATA_BY_ID_PARENT_TOO', // { '5': { ... id: '5', key: "Aatrox" } }
    CHAMPION_LIST: 'DDRAGON.CHAMPION.LIST',
    CHAMPION_LIST_DATA_BY_ID: 'DDRAGON.CHAMPION.HELPER.LIST_DATA_BY_ID', // { Aatrox: { ... id: '5', key: "Aatrox" } }
    CHAMPION_LIST_DATA_BY_ID_PARENT_TOO:
        'DDRAGON.CHAMPION.HELPER.LIST_DATA_BY_ID_PARENT_TOO', // { '5': { ... id: '5', key: "Aatrox" } }
    CHAMPION_LIST_FULL: 'DDRAGON.CHAMPION.LIST_FULL',
    CHAMPION_LIST_FULL_DATA_BY_ID:
        'DDRAGON.CHAMPION.HELPER.LIST_FULL_DATA_BY_ID', // { Aatrox: { ... id: '5', key: "Aatrox" } }
    CHAMPION_LIST_FULL_DATA_BY_ID_PARENT_TOO:
        'DDRAGON.CHAMPION.HELPER.LIST_FULL_DATA_BY_ID_PARENT_TOO', // { '5': { ... id: '5', key: "Aatrox" } }
    CHAMPION_ITEM_LIST: 'DDRAGON.ITEM.LIST',
    LANGUAGE_LIST: 'DDRAGON.LANGUAGE.LIST',
    LANGUAGE_STRING_LIST: 'DDRAGON.LANGUAGE_STRING.LIST',
    MAP: 'DDRAGON.MAP.LIST',
    PROFILE_ICON_LIST: 'DDRAGON.PROFILE_ICON.LIST',
    REALM_LIST: 'DDRAGON.REALM.LIST',
    RUNES_REFORGED_LIST: 'DDRAGON.RUNES_REFORGED.LIST',
    SUMMONER_SPELL_LIST: 'DDRAGON.SUMMONER_SPELL.LIST',
    VERSION_LIST: 'DDRAGON.VERSION.LIST',
}

const LEAGUE = {
    GET_CHALLENGER_LEAGUE: 'LEAGUE.GET_CHALLENGER_LEAGUE',
    GET_ALL_LEAGUES_FOR_SUMMONER: 'LEAGUE.GET_ALL_LEAGUES_FOR_SUMMONER',
    GET_LEAGUE_BY_ID: 'LEAGUE.GET_BY_ID',
    GET_MASTER_LEAGUE: 'LEAGUE.GET_MASTER_LEAGUE',
    GET_ALL_LEAGUE_POSITIONS_FOR_SUMMONER:
        'LEAGUE.GET_ALL_LEAGUE_POSITIONS_FOR_SUMMONER',

    // V4
    GET_CHALLENGER_LEAGUE_V4: 'LEAGUE.GET_CHALLENGER_LEAGUE_V4',
    GET_GRANDMASTER_LEAGUE_V4: 'LEAGUE.GET_GRANDMASTER_LEAGUE_V4',
    GET_LEAGUE_BY_ID_V4: 'LEAGUE.GET_BY_ID_V4',
    GET_MASTER_LEAGUE_V4: 'LEAGUE.GET_MASTER_LEAGUE_V4',
    GET_ALL_POSITIONAL_RANK_QUEUES_V4:
        'LEAGUE.GET_ALL_POSITIONAL_RANK_QUEUES_V4',
    GET_ALL_LEAGUE_POSITIONS_FOR_SUMMONER_V4:
        'LEAGUE.GET_ALL_LEAGUE_POSITIONS_FOR_SUMMONER_V4',
    GET_ALL_POSITIONAL_LEAGUE_ENTRIES_V4:
        'LEAGUE.GET_ALL_POSITIONAL_LEAGUE_ENTRIES_V4',
    GET_LEAGUE_ENTRIES_BY_SUMMONER_ID_V4:
        'LEAGUE.GET_LEAGUE_ENTRIES_BY_SUMMONER_ID_V4',
    GET_LEAGUE_ENTRIES_BY_QUEUE_TIER_DIVISION_V4:
        'LEAGUE.GET_LEAGUE_ENTRIES_BY_QUEUE_TIER_DIVISION_V4',
}

const LOL_STATUS = {
    GET_SHARD_DATA: 'LOL_STATUS.GET_SHARD_DATA',
}

const MATCH = {
    GET_MATCH: 'MATCH.GET_MATCH',
    GET_MATCHLIST: 'MATCH.GET_MATCHLIST',
    GET_MATCH_TIMELINE: 'MATCH.GET_MATCH_TIMELINE',
    GET_MATCH_IDS_BY_TOURNAMENT_CODE: 'MATCH.GET_MATCH_IDS_BY_TOURNAMENT_CODE',
    GET_MATCH_BY_TOURNAMENT_CODE: 'MATCH.GET_MATCH_BY_TOURNAMENT_CODE',

    // V4
    GET_MATCH_V4: 'MATCH.GET_MATCH_V4',
    GET_MATCHLIST_V4: 'MATCH.GET_MATCHLIST_V4',
    GET_MATCH_TIMELINE_V4: 'MATCH.GET_MATCH_TIMELINE_V4',
    GET_MATCH_IDS_BY_TOURNAMENT_CODE_V4:
        'MATCH.GET_MATCH_IDS_BY_TOURNAMENT_CODE_V4',
    GET_MATCH_BY_TOURNAMENT_CODE_V4: 'MATCH.GET_MATCH_BY_TOURNAMENT_CODE_V4',
}

const SPECTATOR = {
    GET_CURRENT_GAME_INFO_BY_SUMMONER:
        'SPECTATOR.GET_CURRENT_GAME_INFO_BY_SUMMONER',
    GET_FEATURED_GAMES: 'SPECTATOR.GET_FEATURED_GAMES',

    // V4
    GET_CURRENT_GAME_INFO_BY_SUMMONER_V4:
        'SPECTATOR.GET_CURRENT_GAME_INFO_BY_SUMMONER_V4',
    GET_FEATURED_GAMES_V4: 'SPECTATOR.GET_FEATURED_GAMES_V4',
}

const SUMMONER = {
    GET_BY_ACCOUNT_ID: 'SUMMONER.GET_BY_ACCOUNT_ID',
    GET_BY_SUMMONER_NAME: 'SUMMONER.GET_BY_SUMMONER_NAME',
    GET_BY_SUMMONER_ID: 'SUMMONER.GET_BY_SUMMONER_ID',

    // V4
    GET_BY_ACCOUNT_ID_V4: 'SUMMONER.GET_BY_ACCOUNT_ID_V4',
    GET_BY_SUMMONER_NAME_V4: 'SUMMONER.GET_BY_SUMMONER_NAME_V4',
    GET_BY_SUMMONER_ID_V4: 'SUMMONER.GET_BY_SUMMONER_ID_V4',
    GET_BY_PUUID_V4: 'SUMMONER.GET_BY_PUUID_V4',
}

const THIRD_PARTY_CODE = {
    GET_BY_SUMMONER_ID: 'THIRD_PARTY_CODE.GET_BY_SUMMONER_ID',

    // V4
    GET_BY_SUMMONER_ID_V4: 'THIRD_PARTY_CODE.GET_BY_SUMMONER_ID_V4',
}

const TOURNAMENT_STUB = {
    CREATE_TOURNAMENT_CODE: 'TOURNAMENT_STUB.CREATE_TOURNAMENT_CODE',
    REGISTER_TOURNAMENT: 'TOURNAMENT.STUB.REGISTER_TOURNAMENT',
    REGISTER_PROVIDER_DATA: 'TOURNAMENT_STUB.REGISTER_PROVIDER_DATA',
    GET_LOBBY_EVENTS_BY_CODE: 'TOURNAMENT_STUB.GET_LOBBY_EVENTS_BY_CODE',

    // V4
    CREATE_TOURNAMENT_CODE_V4: 'TOURNAMENT_STUB.CREATE_TOURNAMENT_CODE_V4',
    REGISTER_TOURNAMENT_V4: 'TOURNAMENT.STUB.REGISTER_TOURNAMENT_V4',
    REGISTER_PROVIDER_DATA_V4: 'TOURNAMENT_STUB.REGISTER_PROVIDER_DATA_V4',
    GET_LOBBY_EVENTS_BY_CODE_V4: 'TOURNAMENT_STUB.GET_LOBBY_EVENTS_BY_CODE_V4',
}

const TOURNAMENT = {
    CREATE_TOURNAMENT_CODE: 'TOURNAMENT.CREATE_TOURNAMENT_CODE',
    UPDATE_TOURNAMENT: 'TOURNAMENT.UPDATE_TOURNAMENT',
    GET_TOURNAMENT_CODE: 'TOURNAMENT.GET_TOURNAMENT.CODE',
    GET_LOBBY_EVENTS_BY_CODE: 'TOURNAMENT.GET_LOBBY_EVENTS_BY_CODE',
    REGISTER_PROVIDER_DATA: 'TOURNAMENT.REGISTER_PROVIDER_DATA',
    REGISTER_TOURNAMENT: 'TOURNAMENT.REGISTER_TOURNAMENT',

    // V4
    CREATE_TOURNAMENT_CODE_V4: 'TOURNAMENT.CREATE_TOURNAMENT_CODE_V4',
    UPDATE_TOURNAMENT_V4: 'TOURNAMENT.UPDATE_TOURNAMENT_V4',
    GET_TOURNAMENT_CODE_V4: 'TOURNAMENT.GET_TOURNAMENT_CODE_V4',
    GET_LOBBY_EVENTS_BY_CODE_V4: 'TOURNAMENT.GET_LOBBY_EVENTS_BY_CODE_V4',
    REGISTER_PROVIDER_DATA_V4: 'TOURNAMENT.REGISTER_PROVIDER_DATA_V4',
    REGISTER_TOURNAMENT_V4: 'TOURNAMENT.REGISTER_TOURNAMENT_V4',
}

export default {
    CHAMPION_MASTERY,
    CHAMPION,
    DDRAGON,
    LEAGUE,
    LOL_STATUS,
    MATCH,
    SPECTATOR,
    SUMMONER,
    THIRD_PARTY_CODE,
    TOURNAMENT_STUB,
    TOURNAMENT,
}
